### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by chrowe** [memetolsen/node-red-grovepi-nodes#6]
I am trying to get this working on a GrovePi running 2017.10.05-Raspbian_For_Robots_by_Dexter_Industries.zip

This seems to come with node v0.10.29 (unless it got updated somehow) but does not come with npm installed. Installing with `sudo apt-get install npm` gives me version `1.4.21`

Running `npm install node-red-grovepi-nodes` (or with sudo) gives me
```
pi@dex:~/.node-red $ npm install node-red-grovepi-nodes
 
> sleep@3.0.1 install /home/pi/.node-red/node_modules/node-red-grovepi-nodes/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/home/pi/.node-red/node_modules/node-red-grovepi-nodes/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
In file included from ../sleep.cc:2:0:
../node_modules/nan/nan.h:331:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
node_sleep.target.mk:82: recipe for target 'Release/obj.target/node_sleep/sleep.o' failed
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-grovepi-nodes/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-grovepi-nodes/node_modules/sleep
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> buffertools@2.1.6 install /home/pi/.node-red/node_modules/node-red-grovepi-nodes/node_modules/node-grovepi/node_modules/buffertools
> node-gyp rebuild



node.js:815
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3
npm ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@3.0.1 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.50-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-grovepi-nodes"
npm ERR! cwd /home/pi/.node-red
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> i2c-bus@1.2.5 install /home/pi/.node-red/node_modules/node-red-grovepi-nodes/node_modules/i2c-bus
> node-gyp rebuild
```
